# Generated by Django 5.1.7 on 2025-04-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikelblog',
            options={'verbose_name_plural': '2. Artikel Blog'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. Kategori'},
        ),
    ]
