# Generated by Django 5.1.7 on 2025-06-29 17:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_komentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikelblog',
            name='konten',
            field=django_ckeditor_5.fields.CKEditor5Field(default='no konten', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
